dev:
  sessions:
    default:
      identity_map_enabled: true
      database: article
      hosts:
        - 192.168.2.14:27017
local:
  sessions:
    default:
      identity_map_enabled: true
      database: amazon
      hosts:
        - 127.0.0.1:27017
chezhongguo:
  sessions:
    default:
      identity_map_enabled: true	
      database: chezhongguo
      hosts:
        - www.baigoosoft.com:27017

